export const personalInfo: string[] = [
	"firstName",
	"lastName",
	"age",
	"heightInches",
	"weight",
	"position",
	"birthDate",
	"college",
	"homeState",
	"homeTown",
	"jerseyNum",
	"handedness",
	"personality",
];

export const ratings: string[] = [
	"speed",
	"strength",
	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"awareness",
	"acceleration",
	"agility",
	"archetype",
	"ballCarrierVision",
	"blockShedding",
	"breakSack",
	"breakTackle",
	"carrying",
	"catchInTraffic",
	"catching",
	"changeOfDirection",
	"deepRouteRunning",
	"finesseMoves",
	"hitPower",
	"impactBlocking",
	"injury",
	"jukeMove",
	"jumping",
	"kickAccuracy",
	"kickPower",
	"kickReturn",
	"leadBlock",
	"manCoverage",
	"zoneCoverage",
	"mediumRouteRunning",
	"powerMoves",
	"pressCoverage",
	"pursuit",
	"release",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"shortRouteRunning",
	"spectacularCatch",
	"spinMove",
	"stamina",
	"stiffArm",
	"tackle",
	"throwUnderPressure",
	"toughness",
	"playAction",
	"playRecognition",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",
	"trucking",
	"throwOnTheRun",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];

export const traits: string[] = [
	"devTrait",
	"qbStance",
	"qbStyle",
	"runningStyle",
	"traitAggressiveCatch",
	"traitBigHitter",
	"traitClutch",
	"traitCoverBall",
	"traitDeepBall",
	"traitDlBullRush",
	"traitDlSpinMove",
	"traitDlSwimMove",
	"traitDropsOpen",
	"traitFightForYards",
	"traitHighMotor",
	"traitLbStyle",
	"traitPenalty",
	"traitPlayBall",
	"traitPossessionCatch",
	"traitPredictability",
	"traitPumpFake",
	"traitRunAfterCatch",
	"traitSensePressure",
	"traitSidelineCatch",
	"traitStripBall",
	"traitTackleLow",
	"traitTendency",
	"traitThrowAway",
	"traitTightSpiral",
	"traitUnk1",
	"traitUnk2",
];

export const appearance: string[] = [
	"portraitId",
	// "genericHead",
	"visuals",
	// "aiPortrait",
	// "aiGenHead",
];

export const extras: string[] = [
	"commentaryId",
	// "visMoveType",
	"visuals",
	"draftPick",
	"draftRound",

	// visuals: object;
];

export const gear: string[] = ["visuals"];

export const qb_ratings: string[] = [
	"br_Passing",

	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"breakSack",
	"throwUnderPressure",
	"playAction",
	"throwOnTheRun",

	"br_Core",
	"speed",
	"strength",
	"awareness",
	"acceleration",
	"agility",
	"changeOfDirection",
	"injury",
	"jumping",
	"stamina",
	"toughness",

	"br_BallCarrier",
	"ballCarrierVision",
	"breakTackle",
	"carrying",
	"jukeMove",
	"spinMove",
	"kickReturn",
	"stiffArm",
	"trucking",

	"br_Receiving",
	"catchInTraffic",
	"catching",
	"spectacularCatch",
	"shortRouteRunning",
	"mediumRouteRunning",
	"deepRouteRunning",
	"release",

	"br_Blocking",
	"impactBlocking",
	"leadBlock",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",

	"br_FrontSeven",
	"blockShedding",
	"finesseMoves",
	"powerMoves",
	"hitPower",
	"pursuit",
	"tackle",

	"br_Coverage",
	"manCoverage",
	"zoneCoverage",
	"pressCoverage",
	"playRecognition",

	"br_Kicking",
	"kickAccuracy",
	"kickPower",

	"archetype",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];

export const rb_ratings: string[] = [
	"br_BallCarrier",
	"ballCarrierVision",
	"breakTackle",
	"carrying",
	"jukeMove",
	"spinMove",
	"kickReturn",
	"stiffArm",
	"trucking",

	"br_Core",
	"speed",
	"strength",
	"awareness",
	"acceleration",
	"agility",
	"changeOfDirection",
	"injury",
	"jumping",
	"stamina",
	"toughness",

	"br_Receiving",
	"catchInTraffic",
	"catching",
	"spectacularCatch",
	"shortRouteRunning",
	"mediumRouteRunning",
	"deepRouteRunning",
	"release",

	"br_Blocking",
	"impactBlocking",
	"leadBlock",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",

	"br_Passing",

	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"breakSack",
	"throwUnderPressure",
	"playAction",
	"throwOnTheRun",

	"br_FrontSeven",
	"blockShedding",
	"finesseMoves",
	"powerMoves",
	"hitPower",
	"pursuit",
	"tackle",

	"br_Coverage",
	"manCoverage",
	"zoneCoverage",
	"pressCoverage",
	"playRecognition",

	"br_Kicking",
	"kickAccuracy",
	"kickPower",

	"archetype",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];

export const wr_ratings: string[] = [
	"br_Receiving",
	"catchInTraffic",
	"catching",
	"spectacularCatch",
	"shortRouteRunning",
	"mediumRouteRunning",
	"deepRouteRunning",
	"release",

	"br_Core",
	"speed",
	"strength",
	"awareness",
	"acceleration",
	"agility",
	"changeOfDirection",
	"injury",
	"jumping",
	"stamina",
	"toughness",

	"br_BallCarrier",
	"ballCarrierVision",
	"breakTackle",
	"carrying",
	"jukeMove",
	"spinMove",
	"kickReturn",
	"stiffArm",
	"trucking",

	"br_Blocking",
	"impactBlocking",
	"leadBlock",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",

	"br_Passing",

	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"breakSack",
	"throwUnderPressure",
	"playAction",
	"throwOnTheRun",

	"br_FrontSeven",
	"blockShedding",
	"finesseMoves",
	"powerMoves",
	"hitPower",
	"pursuit",
	"tackle",

	"br_Coverage",
	"manCoverage",
	"zoneCoverage",
	"pressCoverage",
	"playRecognition",

	"br_Kicking",
	"kickAccuracy",
	"kickPower",

	"archetype",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];

export const te_ratings: string[] = [
	"br_Receiving",
	"catchInTraffic",
	"catching",
	"spectacularCatch",
	"shortRouteRunning",
	"mediumRouteRunning",
	"deepRouteRunning",
	"release",

	"br_Core",
	"speed",
	"strength",
	"awareness",
	"acceleration",
	"agility",
	"changeOfDirection",
	"injury",
	"jumping",
	"stamina",
	"toughness",

	"br_Blocking",
	"impactBlocking",
	"leadBlock",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",

	"br_BallCarrier",
	"ballCarrierVision",
	"breakTackle",
	"carrying",
	"jukeMove",
	"spinMove",
	"kickReturn",
	"stiffArm",
	"trucking",

	"br_Passing",

	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"breakSack",
	"throwUnderPressure",
	"playAction",
	"throwOnTheRun",

	"br_FrontSeven",
	"blockShedding",
	"finesseMoves",
	"powerMoves",
	"hitPower",
	"pursuit",
	"tackle",

	"br_Coverage",
	"manCoverage",
	"zoneCoverage",
	"pressCoverage",
	"playRecognition",

	"br_Kicking",
	"kickAccuracy",
	"kickPower",

	"archetype",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];

export const ol_ratings: string[] = [
	"br_Blocking",
	"impactBlocking",
	"leadBlock",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",
	"br_Core",
	"speed",
	"strength",
	"awareness",
	"acceleration",
	"agility",
	"changeOfDirection",
	"injury",
	"jumping",
	"stamina",
	"toughness",

	"br_BallCarrier",
	"ballCarrierVision",
	"breakTackle",
	"carrying",
	"jukeMove",
	"spinMove",
	"kickReturn",
	"stiffArm",
	"trucking",

	"br_Receiving",
	"catchInTraffic",
	"catching",
	"spectacularCatch",
	"shortRouteRunning",
	"mediumRouteRunning",
	"deepRouteRunning",
	"release",
	"br_Passing",

	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"breakSack",
	"throwUnderPressure",
	"playAction",
	"throwOnTheRun",

	"br_FrontSeven",
	"blockShedding",
	"finesseMoves",
	"powerMoves",
	"hitPower",
	"pursuit",
	"tackle",

	"br_Coverage",
	"manCoverage",
	"zoneCoverage",
	"pressCoverage",
	"playRecognition",

	"br_Kicking",
	"kickAccuracy",
	"kickPower",

	"archetype",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];

export const f7_ratings: string[] = [
	"br_FrontSeven",
	"blockShedding",
	"finesseMoves",
	"powerMoves",
	"hitPower",
	"pursuit",
	"tackle",
	"br_Core",
	"speed",
	"strength",
	"awareness",
	"acceleration",
	"agility",
	"changeOfDirection",
	"injury",
	"jumping",
	"stamina",
	"toughness",

	"br_Coverage",
	"manCoverage",
	"zoneCoverage",
	"pressCoverage",
	"playRecognition",

	"br_BallCarrier",
	"ballCarrierVision",
	"breakTackle",
	"carrying",
	"jukeMove",
	"spinMove",
	"kickReturn",
	"stiffArm",
	"trucking",

	"br_Receiving",
	"catchInTraffic",
	"catching",
	"spectacularCatch",
	"shortRouteRunning",
	"mediumRouteRunning",
	"deepRouteRunning",
	"release",

	"br_Blocking",
	"impactBlocking",
	"leadBlock",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",
	"br_Passing",

	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"breakSack",
	"throwUnderPressure",
	"playAction",
	"throwOnTheRun",

	"br_Kicking",
	"kickAccuracy",
	"kickPower",

	"archetype",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];

export const db_ratings: string[] = [
	"br_Coverage",
	"manCoverage",
	"zoneCoverage",
	"pressCoverage",
	"playRecognition",
	"pursuit",
	"tackle",

	"br_Core",
	"speed",
	"strength",
	"awareness",
	"acceleration",
	"agility",
	"changeOfDirection",
	"injury",
	"jumping",
	"stamina",
	"toughness",

	"br_FrontSeven",
	"blockShedding",
	"finesseMoves",
	"powerMoves",
	"hitPower",

	"br_BallCarrier",
	"ballCarrierVision",
	"breakTackle",
	"carrying",
	"jukeMove",
	"spinMove",
	"kickReturn",
	"stiffArm",
	"trucking",

	"br_Receiving",
	"catchInTraffic",
	"catching",
	"spectacularCatch",
	"shortRouteRunning",
	"mediumRouteRunning",
	"deepRouteRunning",
	"release",

	"br_Blocking",
	"impactBlocking",
	"leadBlock",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",
	"br_Passing",

	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"breakSack",
	"throwUnderPressure",
	"playAction",
	"throwOnTheRun",

	"br_Kicking",
	"kickAccuracy",
	"kickPower",

	"archetype",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];

export const kp_ratings: string[] = [
	"br_Kicking",
	"kickAccuracy",
	"kickPower",

	"br_Core",
	"speed",
	"strength",
	"awareness",
	"acceleration",
	"agility",
	"changeOfDirection",
	"injury",
	"jumping",
	"stamina",
	"toughness",
	"br_FrontSeven",
	"blockShedding",
	"finesseMoves",
	"powerMoves",
	"hitPower",
	"pursuit",
	"tackle",
	"br_Coverage",
	"manCoverage",
	"zoneCoverage",
	"pressCoverage",
	"playRecognition",

	"br_BallCarrier",
	"ballCarrierVision",
	"breakTackle",
	"carrying",
	"jukeMove",
	"spinMove",
	"kickReturn",
	"stiffArm",
	"trucking",

	"br_Receiving",
	"catchInTraffic",
	"catching",
	"spectacularCatch",
	"shortRouteRunning",
	"mediumRouteRunning",
	"deepRouteRunning",
	"release",

	"br_Blocking",
	"impactBlocking",
	"leadBlock",
	"runBlock",
	"runBlockFinesse",
	"runBlockPower",
	"passBlock",
	"passBlockFinesse",
	"passBlockPower",
	"br_Passing",

	"throwPower",
	"throwAccuracyDeep",
	"throwAccuracyMid",
	"throwAccuracyShort",
	"breakSack",
	"throwUnderPressure",
	"playAction",
	"throwOnTheRun",

	"archetype",
	// "unk3",
	// "unk4",
	// "unk5",
	// "unk6",
	// "unk8",
];
